### ISSUE TITLE
[bug] The inference result of the 4xNomos8kSCHAT-S ONNX model is NaN.

### ISSUE THREAD

**Issue by sanbuphy** [OpenModelDB/open-model-database#275]
Thank you very much for sharing [this super-resolution model](https://github.com/Phhofm/models/tree/main/4xNomos8kSCHAT-S) . I tried it and found it effective. However, when I tried to infer the provided fp16 ONNX model, the inference result turned out to be NaN. I wonder if there is any issue with the model (I can get valid results using FP32). Thank you very much.

**Comment by sanbuphy** [comment]
Hi friend @Phhofm , may I ask if you have time to help me look into this issue? Thank you very much. I have tried several ONNX models in the folder, and all of them yield NaN results.

**Comment by Phhofm** [comment]
Hey, hm you could download and try out the version from this gdrive folder (where I have all my model files, and all of them should work with chaiNNer):
https://drive.google.com/drive/folders/1khvw9E1VvlolmHioqKJ5kdKtM1Oka1cQ

I just tested it on my system and it works (screenshot). The thing here is that this is an onnx conversion of the original pth file with 16, so both image dimensions of the input image need to be divisible by 16 otherwise it wont work. In this example I show the cropping to show that, the original input would not work (would throw an error), because one side is 360 pixel. If I in this example crop that side to 352 pixel, it works without problems:
![image](https://github.com/OpenModelDB/open-model-database/assets/14755670/9cc9b5b3-179b-4689-8bae-bca1f867a3cf)

This is the only onnx model file in that folder because chaiNNer currently can not recognize HAT-S (HAT and HAT-L have been around almost a year longer than HAT-S) models, that is why i need that conversion for that model still, otherwise I could simply provide the pth file in that folder (like the other models) and there would hopefully be less problems.

(PS, to use the DAT and SRFormer models in that folder, one would currently need [chaiNNer nightly >= 2023-08-27](https://github.com/chaiNNer-org/chaiNNer-nightly/releases).

**Comment by sanbuphy** [comment]
> Hey, hm you could download and try out the version from this gdrive folder (where I have all my model files, and all of them should work with chaiNNer (the pth files have been resaved with chainner for smaller pth file size)): https://drive.google.com/drive/folders/1khvw9E1VvlolmHioqKJ5kdKtM1Oka1cQ
> 
> I just tested it on my system and it works (screenshot). The thing here is that this is an onnx conversion of the original pth file with 16, so both image dimensions of the input image need to be divisible by 16 otherwise it wont work. In this example I show the cropping to show that, the original input would not work (would throw an error), because one side is 360 pixel. If I in this example crop that side to 352 pixel, it works without problems: ![image](https://user-images.githubusercontent.com/14755670/265431215-9cc9b5b3-179b-4689-8bae-bca1f867a3cf.png)
> 
> This is the only onnx model file in that folder because chaiNNer currently does not recognize HAT-S (HAT and HAT-L have been around almost a year longer than HAT-S) models, that is why i need that conversion for that model still, otherwise I could simply provide the pth file in that folder (like the other models) and there would hopefully be less problems.
> 
> (PS, to use the DAT and SRFormer models in that folder, one would currently need [chaiNNer nightly >= 2023-08-27](https://github.com/chaiNNer-org/chaiNNer-nightly/releases).

Thank you very much for your response! Hello, I did try and was able to generate an image. However, the image has some issues as you can see black patches on it (which matches the results I obtained from direct inference using ONNX Runtime). I suspect this might be due to some layers experiencing numerical instability (which could potentially be mitigated if trained with mixed precision using AMP and FP16). I'm unsure if it's because of training with BF16 and then performing FP16 inference, or if there are inherent issues in the model architecture itself.

![image](https://github.com/OpenModelDB/open-model-database/assets/96160062/9d891ca9-ba49-4b6c-b0c2-cc4708381d15)

![00011-2333](https://github.com/OpenModelDB/open-model-database/assets/96160062/6ad2f578-7ba1-4006-899e-d6fcb4fa5874)

**Comment by sanbuphy** [comment]
> Hm im not sure. Thanks for the report and the results though. And sorry for the inconvenience, it might very well be because im not really versed in onnx conversion/these things.
> 
> I believe I trained it and converted it pretty much the same way I did 4xNomos8kSCHAT-L (but different network params of course for a HAT-L model). Might be that that model (i mean onnx conversion files) suffers from the same thing. I mean it doesnt solve the problem, but if youd like you could try out the 4xNomos8kSCHAT-L.pth instead (with chaiNNer) since the additional onnx conversion step might have given those issues. Its a different model of course, but same training settings and dataset, so should be similiar, (will take longer to run since large model, but might also give a bit better results as tradeoff).

This is an issue caused by the model architecture. Some layers, such as LayerNorm, exhibit significant precision deviations when operating in 16-bit precision. They must be run in FP32 to function properly. However, training with FP16 using automatic mixed precision (AMP) can greatly mitigate this problem. Additionally, you can try inferencing using BF16 if the model was trained with it. I will continue to investigate and if there are any new findings, I will update you. Thank you again for sharing the great model.

**Comment by sanbuphy** [comment]
@Phhofm  Hi , I would like to report a potential strange issue. In images with a large green area, there are strange black shadows visible along the edges. I'm not sure if this is caused by the model data.

![00348-2032716344](https://github.com/OpenModelDB/open-model-database/assets/96160062/00bc681b-a143-416a-9313-eaf5cef7cf30)
![test](https://github.com/OpenModelDB/open-model-database/assets/96160062/f24d29fa-6ab6-4d78-b8bb-d7475517ecb3)
